// Code generated by Kitex v0.3.2. DO NOT EDIT.
package smsservice

import (
	"github.com/cloudwego/kitex/server"
	"ihome/service/user/kitex_gen"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler kitex_gen.SMSService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
