// Code generated by Kitex v0.3.2. DO NOT EDIT.

package captchaservice

import (
	"context"
	"fmt"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	"github.com/cloudwego/kitex/pkg/streaming"
	"google.golang.org/protobuf/proto"
	"ihome/service/captcha/kitex_gen"
)

func serviceInfo() *kitex.ServiceInfo {
	return captchaServiceServiceInfo
}

var captchaServiceServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "CaptchaService"
	handlerType := (*kitex_gen.CaptchaService)(nil)
	methods := map[string]kitex.MethodInfo{
		"GetCaptcha": kitex.NewMethodInfo(getCaptchaHandler, newGetCaptchaArgs, newGetCaptchaResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "captcha",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.3.2",
		Extra:           extra,
	}
	return svcInfo
}

func getCaptchaHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.Request)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.CaptchaService).GetCaptcha(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetCaptchaArgs:
		success, err := handler.(kitex_gen.CaptchaService).GetCaptcha(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetCaptchaResult)
		realResult.Success = success
	}
	return nil
}
func newGetCaptchaArgs() interface{} {
	return &GetCaptchaArgs{}
}

func newGetCaptchaResult() interface{} {
	return &GetCaptchaResult{}
}

type GetCaptchaArgs struct {
	Req *kitex_gen.Request
}

func (p *GetCaptchaArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in GetCaptchaArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *GetCaptchaArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.Request)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetCaptchaArgs_Req_DEFAULT *kitex_gen.Request

func (p *GetCaptchaArgs) GetReq() *kitex_gen.Request {
	if !p.IsSetReq() {
		return GetCaptchaArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetCaptchaArgs) IsSetReq() bool {
	return p.Req != nil
}

type GetCaptchaResult struct {
	Success *kitex_gen.Response
}

var GetCaptchaResult_Success_DEFAULT *kitex_gen.Response

func (p *GetCaptchaResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in GetCaptchaResult")
	}
	return proto.Marshal(p.Success)
}

func (p *GetCaptchaResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.Response)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetCaptchaResult) GetSuccess() *kitex_gen.Response {
	if !p.IsSetSuccess() {
		return GetCaptchaResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetCaptchaResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.Response)
}

func (p *GetCaptchaResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetCaptcha(ctx context.Context, Req *kitex_gen.Request) (r *kitex_gen.Response, err error) {
	var _args GetCaptchaArgs
	_args.Req = Req
	var _result GetCaptchaResult
	if err = p.c.Call(ctx, "GetCaptcha", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
